### ISSUE TITLE
Tim: use Bounds to check validity

### ISSUE THREAD

**Issue by ChikamaYan** [ChikamaYan/arduinoProject#8]
![image](https://user-images.githubusercontent.com/32335747/32212238-ee662404-be0d-11e7-8b5e-eefc8d3858cb.png)

**Comment by ChikamaYan** [comment]
Cannot find a class or type named ��Bounds�� -- processing doesn't seem to have such nice class

**Comment by TimboKZ** [comment]
RIP, you could define your own class then, it's not rocket science.

**Comment by ChikamaYan** [comment]
Then I'll have to use that cancerous 4 part conditional in the class again -- since I really don't need it anywhere else I guess it's not a bad idea to just leave it there.
