### ISSUE TITLE
Tim: code duplication in finding targetx

### ISSUE THREAD

**Issue by ChikamaYan** [ChikamaYan/arduinoProject#9]
![image](https://user-images.githubusercontent.com/32335747/32212379-6c8c9750-be0e-11e7-9484-23a4adb84d96.png)

**Comment by ChikamaYan** [comment]
Fixed -- new function added

**Comment by TimboKZ** [comment]
When I said `function` I didn't mean function in a programming sense, but rather in mathematical sense:

```java
int y = 2x;
random(y); // y is a function of x
```

What you have now is still better since the `moveEnemy()` function now has less lines, which is always good.
